Adds compiler flag driven debugging functions
flipstone/flipstone-prelude pull request #6
Opened 2022-03-03 20:44 UTC by AugmenTab

This adds a new module `Flipstone.Debug`, which conditionally
exports debugging functions with different type signatures
depending on the presence of a `DEV` compiler flag. When the flag
is present, the debugging functions have the expected behavior.
When the flag is not present, they instead will have a type
`DevFlagNotSet` that won't match and will cause the app to fail.

Co-authored-by: Ava <ava@flipstone.com>
Co-authored-by: James <james@flipstone.com>

2022-03-03 20:51 UTC, OwenGraves approved these changes
Neat idea!

2022-03-03 20:51 UTC, OwenGraves commented on src/Flipstone/Debug.hs
> +-- environments. They will only compile if there is a `-DDEV` compiler flag
Does `-DDEV` refer to "DEV" in the `ifdef` here?

2022-03-03 21:05 UTC, exodrifter commented on src/Flipstone/Debug.hs
> +-- environments. They will only compile if there is a `-DDEV` compiler flag
That's correct. It's one of the [C pre-processor flags](https://downloads.haskell.org/ghc/latest/docs/html/users_guide/phases.html#ghc-flag--D%E2%9F%A8symbol%E2%9F%A9[=%E2%9F%A8value%E2%9F%A9]) which GHC accepts.

2022-03-03 21:23 UTC, ysangkok commented
Did you consider defining a cabal flag that toggles the CPP definition such that this can be toggled through that mechanism instead of globally setting `cpp-options`?

Wims uses hlint to prevent usage of Debug.Trace, I wonder how that compares to this. It seems like both methods can achieve the same goal of preventing debugging code from passing CI. One difference is that, the hlint method requires an additional step, while this integrates with `-Werror` and can fail the compilation in that manner. Is that correct?

I am not sure whether [modulint](https://github.com/flipstone/modulint) provides the ability to forbid a certain module, do you know @telser ?

2022-03-03 21:29 UTC, qxjit commented on src/Flipstone/Debug.hs
> +data DevFlagNotSet
I would use `TypeError` for this so that we have nice control over the compiler error message

2022-03-03 21:30 UTC, qxjit requested changes

2022-03-03 21:30 UTC, qxjit commented on flipstone-prelude.cabal
> +      NoImplicitPrelude
I expected to see a built flag definition somewhere in the cabal file here. I definitely think we should use that mechanism to control this.

2022-03-04 16:10 UTC, jbrechtel commented on src/Flipstone/Debug.hs
> +data DevFlagNotSet
Oh nice, that seems like a great option here

2022-03-23 22:48 UTC, ysangkok commented
@AugmenTab 

what I was thinking is something like the following:

```
flag debug
   manual: true
```

then down in the library section, you add

```
if flag(debug)
    cpp-options: -DDEV
```

The flag can then be set using e.g. `cabal build flipstone-prelude -f debug` or [set using a configuration file with stack](https://docs.haskellstack.org/en/stable/yaml_configuration/#flags).

This syntax may be wrong and is probably more like cabal syntax, while you'd wanna write it with hpack syntax. If you still need help, let me know.

2022-03-24 14:56 UTC, ysangkok commented on flipstone-prelude.cabal
> +  description: _
Looks like you actually wrote a description? I think the cabal file needs regenerating.

2022-03-24 14:56 UTC, telser commented on package.yaml
> +  - CPP
FWIW I think we should not turn on CPP by default. As it is we only use it in one place, so we can be very specific there.

2022-03-24 15:03 UTC, merged